#server port
server: 
  port: 9091

#DB
spring: 
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe 
    username: SPRING
    password: SPRING
    # JPA connection pool 관리
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: false
      connection-test-query: select 1 from dual
      pool-name: dmpool
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      

# view화면 jsp 연결
  mvc: 
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  
  #업로드 파일 크기 제한 설정
  servlet: 
    multipart: 
      max-file-size: 10MB
      max-request-size: 10MB
  
        
#mybatis
#mybatis: 
#  config-location: classpath:/config/mybatis-config.xml
#  mapper-locations: classpath:/mapper/**/*.xml

# 고정데이터 입력(custom)
# 기본 경로, 기본 포트, 계정관련내용
linux: 
  url: localhost:8989
  username: root
  base: /home/dm

# 로그에 대한 설정하기
logging:
  file:
    name: logs/springboot.log
  level:
    root: info
    '[com.dm.springboot]': warn
  






  